values:
  couchbase:
    host: "localhost"
    username: "Administrator"
    password: "Administrator"
    Buckets:
      inventory:
        bucketName: "inventory"
        keyLength: 10
      notify_Customer:
        bucketName: "notify_Customer"
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notifyConsumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
    #        auto-offset-reset: earliest
    #        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      retry:
        maxAttempts: 3
    #        key-serializer: org.apache.kafka.common.serialization.StringSerializer
    #        value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic: notify_Customer
  mail:
    host: "smtp.gmail.com"
    port: "587"
    username: "yogimoun009@gmail.com"
    password: "--"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
